import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    background: #313e50;
    GridLayout {
        padding: 50px;
        spacing: 25px;

        Row {
            Text {
                text: "Enter total income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }
        Row {
            LineEdit {
                placeholder-text: "Enter your number";
                horizontal-alignment: center;
                font-size: 16px;
                height: 35px;
            }
        }
        Row {
            Button {
                text: "Calculate";
                primary: true;
                height: 35px;
                clicked => { self.text = "Clicked"; }
            }
        }
    }
}
